config/routes.rb
Rails.application.routes.draw do
  get 'tasks/new'
  devise_for :users
  root to: "pages#home", as: :home

  resources :lists do
    resources :tasks, only: %i[index new create]
  end
  resources :tasks, only: %i[show edit update]

  resources :tasks, only: [:destroy], as: :destroytask

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_list, only: %i[destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @list = List.find(params[:list_id])
    @task.list = @list
    @task.save
    redirect_to list_path(@list)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to list_path(@task.list)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def task_params
    params.require(:task).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListPixelpay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= link_to "Cancelar", list_path(@list), class: "btn btn-warning" %>
      <%= form_with model: @list do |f| %>
        <%= f.label "Nuevo nombre:" %>
        <%= f.text_field :name %>
        <%= f.submit "Actualizar Lista", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
    <%= link_to "Crear nueva Lista de Tareas", new_list_path, class: "btn btn-primary" %>
      <ul>
        <% @lists.each do |list| %>
          <li class="listItem"><%= link_to list.name, list_path(list) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col12">
      <h1 class="text-center">Nueva Lista de tareas</h1>
      <%= link_to "Cancelar", lists_path, class: "btn btn-warning" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 d-flex justify-content-center">
      <%= form_with model: @list do |f| %>
        <%= f.label "Nombre:" %>
        <%= f.text_field :name %>
        <%= f.submit "Crear Lista", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= link_to "Ver todas las listas", lists_path, class: "btn btn-success" %>
      <%= link_to "Editar nombre de lista", edit_list_path, class: "btn btn-dark" %>
      <%= link_to "Eliminar lista",
        list_path(@list), class: "btn btn-danger",
        data: {turbo_method: :delete, turbo_confirm: "¿Estás seguro?"}
      %>
      <h2><%= @list.name %></h2>

      <p><strong>Tareas:</strong></p>
      <ul class="list-group">
        <% @list.tasks.each do |task| %>
          <li class="list-group-item">
            <%= task.content %>
            <%= link_to "Editar Tarea", edit_task_path(task), class: "btn btn-dark" %>
            <%= link_to "Eliminar Tarea",
              destroytask_path(task), class: "btn btn-danger",
              data: {turbo_method: :delete, turbo_confirm: "¿Estás seguro?"}
            %>
          </li>
        <% end %>
      </ul>

      <%= link_to "Crear nueva tarea", new_list_task_path(@list), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="text-center">Listas de Tareas - Pixelpay</h1>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <ul>
        <% @lists.each do |list| %>
          <li><%= list.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= link_to "Volver al inicio", home_path %>
      <h2><%= @list.name %></h2>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to home_path, class: "navbar-brand" do %>
      <%= image_tag "https://cms-assets.tutsplus.com/cdn-cgi/image/width=850/uploads/users/523/posts/32694/final_image/tutorial-preview-large.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Inicio", home_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Listas", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://avatars.githubusercontent.com/u/68158101?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<hr/>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= link_to 'Cancelar', :back, class: "btn btn-warning"  %>
      <%= form_with model: @task do |f| %>
        <%= f.label "Nuevo nombre:" %>
        <%= f.text_field :content %>
        <%= f.submit "Actualizar Tarea", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col12">
      <h1 class="text-center">Nueva Tarea</h1>
      <%= link_to "Cancelar", list_path(@list), class: "btn btn-warning" %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 d-flex justify-content-center">
      <%= form_with model: [@list, @task] do |f| %>
        <%= f.label "Nombre:" %>
        <%= f.text_field :content %>
        <%= f.submit "Crear Tarea", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>